#config_version=5

mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 20
      - type: text
        text: PLAYER (number)
        y: 5
        x: 10
        font_size: 5
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 5
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 5

# Swith hit, MPF posts <switch_name>_active event
# Switch released, MPF posts <switch_name>_inactive event
variable_player:
  s_left_flipper_active:
    score: 100
  s_right_flipper_active:
    score: 1000
  s_left_slingshot_active:
    score: 500
  s_right_slingshot_active:
    score: 500 