#config_version=6

mode:
  start_events: ball_started
  priority: 100

event_player:
  mode_base_started:
    - start_mode_attack_bumper_upgrade
  mode_base_will_stop:
    - stop_mode_attack_bumper_upgrade

slide_player:
  mode_base_started: base_slide

sound_player:
  ball_drain:
    ball_end:
      action: play
      loops: 0
  s_re-entry_lane_left_active:
    rollover_switch:
      action: play
      loops: 0
  s_re-entry_lane_middle_active:
    rollover_switch:
      action: play
      loops: 0
  s_re-entry_lane_right_active:
    rollover_switch:
      action: play
      loops: 0

# Switch hit, MPF posts <switch_name>_active event
# Switch released, MPF posts <switch_name>_inactive event
# Some temporary scores for testing
variable_player:
  s_flipper_button_left_active:
    score: 100
  s_flipper_button_right_active:
    score: 1000
  s_rebound_lower_left_active:
    score: 500
  s_rebound_lower_right_active:
    score: 500
    