#config_version=6

mode:
  start_events: ball_will_start
#  start_events: mode_game_started_sound_ended
  priority: 100

queue_relay_player:
  ball_starting:
    post: start_ball_eject_sound
    wait_for: mode_ball_eject_sound_ended
  ball_ending:
    post: start_ball_drain_sound
    wait_for: mode_ball_drain_sound_ended

event_player:
  mode_base_started:
    - start_mode_attack_bumper_upgrade
  mode_base_will_stop:
    - stop_mode_attack_bumper_upgrade

slide_player:
  mode_base_started: base_slide

sound_player:
  start_ball_eject_sound:
    ball_trough_eject:
      action: play
      loops: 0
      events_when_stopped: mode_ball_eject_sound_ended
  start_ball_drain_sound:
    ball_end:
      action: play
      loops: 0
      events_when_stopped: mode_ball_drain_sound_ended 
  s_re-entry_lane_left_active:
    rollover_switch:
      action: play
      loops: 0
  s_re-entry_lane_middle_active:
    rollover_switch:
      action: play
      loops: 0
  s_re-entry_lane_right_active:
    rollover_switch:
      action: play
      loops: 0
  s_outlane_right_active:
    rollover_switch:
      action: play
      loops: 0
  s_inlane_right_active:
    rollover_switch:
      action: play
      loops: 0
  s_outlane_left_active:
    rollover_switch:
      action: play
      loops: 0
  s_inlane_refuel_left_active:
    refuel_rollover_switch:
      action: play
      loops: 0
  s_inlane_left_active:
    rollover_switch:
      action: play
      loops: 0


# Switch hit, MPF posts <switch_name>_active event
# Switch released, MPF posts <switch_name>_inactive event
# Some temporary scores for testing
variable_player:
  s_flipper_button_left_active:
    score: 100
  s_flipper_button_right_active:
    score: 1000
  s_rebound_lower_left_active:
    score: 500
  s_rebound_lower_right_active:
    score: 500
    