#config_version=6

# Notes:
# - Coils are grouped per board, boards are listed in loop order

coils:
  # Cabinet I/O ----------------------------------------------------------
  # 6 low current drivers (L0-L5)
  # 1 high current driver (D1)
  # cabinet_io-0 Unused
  # cabinet_io-1 Unused
  c_start_button_light:
    number: cabinet_io-2
    allow_enable: true
    label: "Start Button Light"
  # cabinet_io-3 Unused
  # cabinet_io-4 Unused
  # cabinet_io-5 Unused


  # 3208 (Lower Third) ---------------------------------------------------
  # 8 high current driver (0-7)
  c_flipper_left_main:
    number: lower_io-0
    default_pulse_ms: 10 # TODO - dial this number if coils are too weak, try 5ms increments
  c_flipper_left_hold:
    number: lower_io-1
    allow_enable: true
  c_flipper_right_main:
    number: lower_io-2
    default_pulse_ms: 10 # TODO - dial this number if coils are too weak, try 5ms increments
  c_flipper_right_hold:
    number: lower_io-3
    allow_enable: true
  c_save_post:
    number: lower_io-4
    # DO NOT use allow_enable true for this coil, that setting will
    # use 100% power for holding which will burn up the coil!
    # 0.0-1.0 (0% - 100%)
    # TODO - investigate PWM hold for this coil
    default_hold_power: 0.1
  c_trough_eject:
    number: lower_io-5
    default_pulse_ms: 10
  c_outlane_kicker_left:
    number: lower_io-6
    default_pulse_ms: 10
  c_outlane_kicker_right:
    number: lower_io-7
    default_pulse_ms: 10


  # 1616 (Middle Third) --------------------------------------------------
  # 16 high current drivers (0-15)
  c_auto_launcher:
    number: middle_io-0
    default_pulse_ms: 10
  c_rebound_lower_right:
    number: middle_io-1
    default_pulse_ms: 5
  c_rebound_lower_left:
    number: middle_io-2
    default_pulse_ms: 5
  c_drop_targets_medal:
    number: middle_io-3
    default_pulse_ms: 20
  c_drop_targets_multiplier:
    number: middle_io-4
    default_pulse_ms: 25
  # middle_io-5 Unused
  # middle_io-6 Unused
  # middle_io-7 Unused
  # middle_io-8 Unused
  # middle_io-9 Unused
  # middle_io-10 Unused
  # middle_io-11 Unused
  # middle_io-12 Unused
  # middle_io-13 Unused
  # middle_io-14 Unused
  # middle_io-15 Unused


  # 3208 (Upper Third) ---------------------------------------------------
  # 8 high current drivers (0-7)
  c_attack_bumper_middle:
    number: upper_io-0
    default_pulse_ms: 5
  c_attack_bumper_right:
    number: upper_io-1
    default_pulse_ms: 5
  c_attack_bumper_left:
    number: upper_io-2
    default_pulse_ms: 5
  c_attack_bumper_upper_left:
    number: upper_io-3
    default_pulse_ms: 5
  c_scoop_red_wormhole:
    number: upper_io-4
    default_pulse_ms: 10
  # upper_io-5 Unused
  # upper_io-6 Unused
  # upper_io-7 Unused
  