#config_version=6

config:
  - coils.yaml
  - devices.yaml
  #- leds.yaml
  - sounds.yaml
  - switches.yaml

displays:
  dmd:
    width: 128
    height: 32
    default: true

fast:
  net:
    controller: neuron
    port: COM8
    io_loop:
      cabinet_io:
        model: FP-I/O-0024
        order: 1
      lower_io:
        model: FP-I/O-3208
        order: 2
      middle_io:
        model: FP-I/O-1616
        order: 3
      upper_io:
        model: FP-I/O-3208
        order: 4
    baud: 921600
    debug: false
    console_log: none
    file_log: basic
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  exp:
    boards:
      neuron:
        model: FP-EXP-2000
      playfield:
        model: FP-EXP-0071
        led_fade_time: 0
    port: auto
    baud: 921600
    debug: false
  # exp:
  #   port: COM9
  #   boards:
  #     neuron:
  #       model: FP-EXP-2000
  #       breakouts:
  #         - port: 1
  #           model: FP-PWR-0007
  #       led_ports:
  #         - port: 1
  #           leds: 20
  #           type: ws2812
  # lights:
  #   led1:
  #     number: neuron-1-1

game:
  balls_per_game: 3
  max_players: 4

hardware:
  #platform: fast
  platform: smart_virtual

modes:
  - attack_bumper_upgrade
  - attract
  - base
  - medal
  - skillshot

player_vars:
  multiplier:
    value_type: int
    initial_value: 1

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
