#config_version=6

config:
  - coils.yaml
  - devices.yaml
  - lights.yaml
  - sounds.yaml
  - switches.yaml

hardware:
  platform: fast
  driverboards: fast
  coils: fast
  hardware_sound_system: fast

# Fast boards should show up on ports /dev/ttyACM0 - /dev/ttyACM2
# User needs dialout group permissions to access these ports
fast:
  net:
    controller: neuron
    port: auto
    io_loop:
      cabinet_io:
        model: FP-I/O-0024
        order: 1
      lower_io:
        model: FP-I/O-3208
        order: 2
      middle_io:
        model: FP-I/O-1616
        order: 3
      upper_io:
        model: FP-I/O-3208
        order: 4
    baud: 921600
    debug: false
    console_log: none
    file_log: basic
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  exp:
    debug: false
    port: auto
    baud: 921600
    boards:
      neuron_exp:
        model: FP-EXP-2000
      playfield_exp:
        model: FP-EXP-0081
  aud:
    debug: false
    port: auto
    baud: 230400
    main_amp_enabled: true
    sub_amp_enabled: true
    headphones_amp_enabled: false

    main_steps: 20
    sub_steps: 20
    headphones_steps: 20

    default_main_volume: 40
    default_sub_volume: 30
    default_headphones_volume: 16

    persist_volume_settings: true

    max_hw_volume_main: 63
    max_hw_volume_sub: 63
    max_hw_volume_headphones: 63

    main_levels_list: None
    sub_levels_list: None
    headphones_levels_list: None

    link_sub_to_main: true
    link_headphones_to_main: false

    headphones_level: headphones
    mute_speakers_with_headphones: true

game:
  balls_per_game: 3
  max_players: 4

modes:
  - attack_bumper_upgrade
  - attract
  - base
  - medal
  - multiplier
  - skillshot

player_vars:
  multiplier:
    value_type: int
    initial_value: 1

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
