#config_version=5

# autofire_coils:
#     lower_left_sling:
#         coil:
#         switch:
#     lower_right_sling:
#         coil:
#         switch:
#     upper_left_sling:
#         coil:
#         switch:
#     upper_right_sling:
#         coil:
#         switch:
#     attack_bumper_1:
#         coil:
#         switch:
#     attack_bumper_2:
#         coil:
#         switch:
#     attack_bumper_3:
#         coil:
#         switch:
#     attack_bumper_4:
#         coil:
#         switch:
    # launch_bumper_1:
    #     coil:
    #     switch:
    # launch_bumper_2:
    #     coil:
    #     switch:
    # launch_bumper_3:
    #     coil:
    #     switch:

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper_button
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper_button

ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough_jam
        eject_coil: c_trough_eject
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms
        eject_targets: bd_plunger
        eject_timeouts: 3s
    bd_plunger:
        ball_switches: s_plunger_lane
        mechanical_eject: true
        eject_timeouts: 5s