#config_version=6

# Note - Non-standard characters need to be in quotes
keyboard:
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  7:
    switch: s_re-entry_lane_left
  8:
    switch: s_re-entry_lane_middle
  9:
    switch: s_re-entry_lane_right
  p:
    switch: s_plunger_lane
    toggle: true
  s:
    switch: s_start_button
  t:
    switch: s_tilt
  z:
    switch: s_flipper_button_left
  /:
    switch: s_flipper_button_right